#1 List the number of films per category
USE SAKILA;
select category.name,count(film.film_id) 
from category join film_category on category.category_id=film_category.category_id
join film on film_category.film_id=film.film_id group by category.name;

#2  Retrieve the store ID, city, and country for each store.
select store.store_id,city.city,country.country 
from store join address on store.address_id=address.address_id
join city on address.city_id=city.city_id
join country on city.country_id=country.country_id;

#3 Calculate the total revenue generated by each store in dollars.
select store.store_id,round(sum(payment.amount),0) as 'revenue in $'
from store join staff on store.store_id=staff.store_id
join payment on staff.staff_id=payment.staff_id group by store.store_id;

#4 Determine the average running time of films for each category.
select * from category;
select category.name,round(avg(film.length),0) as 'avg running time' 
from category join film_category on category.category_id=film_category.category_id
join film on film_category.film_id=film.film_id
group by category.name;

#5 Identify the film categories with the longest average running time.
select category.name,round(avg(film.length),0) as 'avg running time' 
from category join film_category on category.category_id=film_category.category_id
join film on film_category.film_id=film.film_id
group by category.name 
order by round(avg(film.length),0) desc 
limit 2;

#6 Display the top 10 most frequently rented movies in descending order.
select film.title, count(rental.rental_id) as 'mode'
from film join inventory on film.film_id=inventory.film_id
join rental on inventory.inventory_id=rental.inventory_id 
group by film.title order by count(rental.rental_id) desc limit 10;

#7 Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT IF(COUNT(*) > 0, 'Yes', 'No') AS can_be_rented
FROM film
JOIN inventory USING (film_id)
WHERE film.title LIKE '%Academy Dinosaur%'
  AND inventory.store_id = 1;

#another way
select film.title,if(count(inventory_id)>0,'Yes','No') as 'Can be rented'
from film join inventory on film.film_id=inventory.film_id
where film.title='%Academy Dinosaur%' and inventory.store_id=1;





